apiVersion: v1
kind: Service
metadata:
  name: tp-mongo-ingress-nginx
  #namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: tp-mongo-ingress-nginx
    app.kubernetes.io/part-of: tp-mongo-ingress-nginx
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: <DO_LOADBALANCER_ID>
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  loadBalancerIP: <EXTERNAL_DO_IP>
  selector:
    app: tp-apis
  ports:
    - port: 27017
      targetPort: 27017
      #protocol: TCP
      nodePort: 31400
  externalIPs: 
    - <EXTERNAL_DO_IP>
