apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-apis
  labels:
    app: tp-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-apis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tp-apis
    spec:
      volumes:
        - name: tp-mongo-data-pv
          persistentVolumeClaim:
            claimName: tp-mongo-data
        - name: tp-rabbitmq-pv
          persistentVolumeClaim:
            claimName: tp-rabbit-data
        - name: tp-postgres-data-pv
          persistentVolumeClaim:
            claimName: tp-postgres-data
      restartPolicy: Always
      #hostname: tprabbitmq
      containers:
      - name: tpostgres
        image: postgres:12
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tp-postgres-data-pv
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-data
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-data
                  key: postgres-username
        ports:
            - containerPort: 5432
      - name: tpmongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
            - mountPath: /data/db
              name: tp-mongo-data-pv
        env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-username
      - name: tprabbitmq
        image: rabbitmq:3.9-management
        ports:
            - containerPort: 5672
            - containerPort: 15672
        volumeMounts:
            - mountPath: /etc/rabbitmq/rabbitmq.conf
              name: tp-rabbitmq-pv
            - mountPath: /etc/rabbitmq/definitions.json
              name: tp-rabbitmq-pv
            - mountPath: /var/lib/rabbitmq/mnesia
              name: tp-rabbitmq-pv
            - mountPath: /var/log/rabbitmq
              name: tp-rabbitmq-pv
        env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-data
                  key: rabbitmq-password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-data
                  key: rabbitmq-username
      - name: tpgateway
        image: <GATEWAY_API_IMAGE>
        ports:
            - containerPort: 3005
        env:
            - name: ASPNETCORE_URLS
              value: "http://+:3005"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ApplicationSettings__Cors
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: gateway-cors-urls
            - name: JWT__RefreshTokenValidityInDays
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: refresh-token-validity-days
            - name: JWT__SecretPublicKey
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: jwt-public-secret
            - name: JWT__TokenValidityInMinutes
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: jwt-token-validity-minutes
            - name: JWT__ValidAudience
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: jwt-valid-audience
            - name: JWT__ValidIssuer
              valueFrom:
                  secretKeyRef:
                      name: gateway-data
                      key: jwt-valid-issuer
      - name: tpemailservice
        image: <EMAILSERVICE_API_IMAGE>
        ports:
            - containerPort: 3010
        env:
            - name: ASPNETCORE_URLS
              value: "http://+:3010"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ApplicationSettings__RabbitMQHost
              valueFrom:
                  secretKeyRef:
                      name: emailservice-data
                      key: rabbitmq-host
            - name: ApplicationSettings__RabbitMQPassword
              valueFrom:
                  secretKeyRef:
                      name: emailservice-data
                      key: rabbitmq-password
            - name: ApplicationSettings__RabbitMQUser
              valueFrom:
                  secretKeyRef:
                      name: emailservice-data
                      key: rabbitmq-username
            - name: ConnectionStrings__Database
              valueFrom:
                  secretKeyRef:
                      name: emailservice-data
                      key: db-name
            - name: ConnectionStrings__DefaultConnectionString
              valueFrom:
                  secretKeyRef:
                      name: emailservice-data
                      key: db-conn-string
      - name: tpuserservice
        image: <USERSERVICE_API_IMAGE>
        ports:
            - containerPort: 3020
        env:
            - name: ASPNETCORE_URLS
              value: "http://+:3020"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ApplicationSettings__RabbitMQHost
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: rabbitmq-host
            - name: ApplicationSettings__RabbitMQPassword
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: rabbitmq-password
            - name: ApplicationSettings__RabbitMQUser
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: rabbitmq-username
            - name: ApplicationSettings__RecoverPasswordBaseUrl
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: frontend-recover-base-url
            - name: ConnectionStrings__DefaultConnectionString
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: db-conn-string
            - name: JWT__SecretPrivateKey
              valueFrom:
                  secretKeyRef:
                      name: user-private-key-secret
                      key: user-privatekey
            - name: JWT__RefreshTokenValidityInDays
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: refresh-token-validity-days
            - name: JWT__SecretPublicKey
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: jwt-public-secret
            - name: JWT__TokenValidityInMinutes
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: jwt-token-validity-minutes
            - name: JWT__ValidAudience
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: jwt-valid-audience
            - name: JWT__ValidIssuer
              valueFrom:
                  secretKeyRef:
                      name: userservice-data
                      key: jwt-valid-issuer
      imagePullSecrets:
      - name: do-photos-registry-secret
