apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-apis
  labels:
    app: tp-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-apis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tp-apis
    spec:
      volumes:
        - name: tp-mongo-data-pv
          persistentVolumeClaim:
            claimName: odoo-app-data
      containers:
      - name: tp-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
            - mountPath: /data/db
              name: tp-mongo-data-pv
        env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-username
      imagePullSecrets:
      - name: do-photos-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tp-mongo-service
  labels:
    run: tp-mongo-service
spec:
  ports:
    - port: 27018
      targetPort: 27017
  selector:
    app: tp-apis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-apis-ingress-nginx-controller
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      service.beta.kubernetes.io/do-loadbalancer-protocol: https
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  tls:
  - hosts:
    - tpapi.chain-of-change.com
    secretName: transportugal-apis-tls-secret
  rules:
  - host: tpapi.chain-of-change.com
  type: LoadBalancer
  ports:
    - name: mongodriver
      port: 27018
      targetPort: 27018
      protocol: TCP
  selector:
    app.kubernetes.io/name: tp-apis-ingress-nginx-controller
    app.kubernetes.io/part-of: tp-apis-ingress-nginx-controller
