apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-apis
  labels:
    app: tp-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-apis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tp-apis
    spec:
      volumes:
        - name: tp-mongo-data-pv
          persistentVolumeClaim:
            claimName: odoo-app-data
      containers:
      - name: tp-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
            - mountPath: /data/db
              name: tp-mongo-data-pv
        env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-data
                  key: mongo-username
      imagePullSecrets:
      - name: do-photos-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tp-mongo-ingress-nginx
  #namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: tp-mongo-ingress-nginx
    app.kubernetes.io/part-of: tp-mongo-ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  selector:
    app: tp-apis
  ports:
    - port: 27017
      targetPort: 27017
      #protocol: TCP
      nodePort: 31400
  externalIPs: 
    - 67.207.68.112
