apiVersion: v1
kind: Service
metadata:
  name: tp-rabbitmq-service
  labels:
    run: tp-rabbitmq-service
spec:
  ports:
    - port: 31000
      targetPort: 15672
  selector:
    app: tp-apis
---
apiVersion: v1
kind: Service
metadata:
  name: tp-gatewayapi-service
  labels:
    run: tp-gatewayapi-service
spec:
  ports:
    - port: 31010
      targetPort: 3005
  selector:
    app: tp-apis
---
apiVersion: v1
kind: Service
metadata:
  name: tp-cms-service
  labels:
    run: tp-cms-service
spec:
  ports:
    - port: 31020
      targetPort: 1337
  selector:
    app: tp-apis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-rabbitmq-ingress-nginx-controller
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: tp-issuer-letsencrypt
      service.beta.kubernetes.io/do-loadbalancer-protocol: https
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  tls:
  - hosts:
    - rabbit.transicaoportugal.org
    secretName: tp-rabbit-letsencrypt-crt-secret
  rules:
  - host: rabbit.transicaoportugal.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: tp-rabbitmq-service
            port:
              number: 31000
              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-gatewayapi-ingress-nginx-controller
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: tp-issuer-letsencrypt
      service.kubernetes.io/do-loadbalancer-protocol: https
      service.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  tls:
  - hosts:
    - tpapi.transicaoportugal.org
    secretName: tp-gateway-letsencrypt-crt-secret
  rules:
  - host: tpapi.transicaoportugal.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: tp-gatewayapi-service
            port:
              number: 31010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-cms-ingress-nginx-controller
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: tp-issuer-letsencrypt
      service.kubernetes.io/do-loadbalancer-protocol: https
      service.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  tls:
  - hosts:
    - cms.transicaoportugal.org
    secretName: tp-cms-letsencrypt-crt-secret
  rules:
  - host: cms.transicaoportugal.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: tp-cms-service
            port:
              number: 31020
