apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpdiscourse-redis-data
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: tpdiscourse
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tp-discourse-data
  namespace: default
spec:
  #storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
