apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-discourse
  labels:
    app: tp-discourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-discourse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tp-discourse
    spec:
      volumes:
        - name: discourse-data
          persistentVolumeClaim:
            claimName: tp-discourse-data
        - name: default-token-97f74
          secret:
            secretName: default-token-97f74
            defaultMode: 420
      restartPolicy: Always
      hostname: tpdiscoursepod
      containers:
      - name: discourse
        image: docker.io/bitnami/discourse:2.8.3-debian-10-r7
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        envFrom:
          - configMapRef:
              name: my-release-discourse
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: DISCOURSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-release-discourse-discourse
              key: discourse-password
        - name: DISCOURSE_PORT_NUMBER
          value: '8080'
        - name: DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER
          value: '80'
        - name: DISCOURSE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpdiscourse-data
              key: database-password
        - name: POSTGRESQL_CLIENT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpdiscourse-data
              key: database-password
        - name: DISCOURSE_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpdiscourse-data
              key: redis-password
        volumeMounts:
        - name: discourse-data
          mountPath: /bitnami/discourse
          subPath: discourse
        - name: default-token-97f74
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        livenessProbe:
          httpGet:
            path: /srv/status
            port: http
            scheme: HTTP
          initialDelaySeconds: 500
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /srv/status
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: sidekiq
        image: docker.io/bitnami/discourse:2.8.3-debian-10-r7
        command:
          - /opt/bitnami/scripts/discourse/entrypoint.sh
        args:
          - /opt/bitnami/scripts/discourse-sidekiq/run.sh
        envFrom:
          - configMapRef:
              name: my-release-discourse
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: DISCOURSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-release-discourse-discourse
              key: discourse-password
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpdiscourse-data
              key: database-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpdiscourse-data
              key: redis-password
        volumeMounts:
          - name: discourse-data
            mountPath: /bitnami/discourse
            subPath: discourse
          - name: default-token-97f74
            readOnly: true
            mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - pgrep -f ^sidekiq
          initialDelaySeconds: 500
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - pgrep -f ^sidekiq
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent 
