apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-discourse
  labels:
    app: tp-discourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-discourse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tp-discourse
    spec:
      volumes:
        - name: tp-discourse-pv
          persistentVolumeClaim:
            claimName: tp-discourse-data
        - name: tp-discourse-sidekiq-pv
          persistentVolumeClaim:
            claimName: tp-discourse-sidekiq-data
      restartPolicy: Always
      hostname: tpdiscoursepod
      containers:
      - name: tpdiscoursebase
        image: geoffreychallen/discourse_base:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        env:
            - name: DISCOURSE_HOSTNAME
              value: tpdiscourse.chain-of-change.com
            - name: DISCOURSE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tpdiscourse-data
                  key: database-user
            - name: DISCOURSE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpdiscourse-data
                  key: database-password
            - name: DISCOURSE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tpdiscourse-data
                  key: database-host
            - name: DISCOURSE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tpdiscourse-data
                  key: database-name
            - name: DISCOURSE_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: tpdiscourse-data
                  key: database-port
      
