version: '3.4'

services:
  tpgateway:
    image: ${DOCKER_REGISTRY-}tpgateway
    container_name: tp_gateway
    build:
        context: .
        dockerfile: tpgateway.dockerfile
    ports:
        - "5000:80"
    networks:
        - tp_bridge

networks:
    tp_bridge:
        name: tp_bridge
        driver: bridge