# Generated by Django 2.2.28 on 2022-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=30)),
                ('Value', models.CharField(max_length=300)),
                ('DefaultValue', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=100)),
                ('SettingType', models.IntegerField()),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('UpdatedBy', models.CharField(max_length=100)),
            ],
        ),
    ]
