# Generated by Django 2.2.28 on 2022-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='UpdatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='UpdatedBy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
