name: transition pt discourse Build and Deploy

on:
  push:
    branches: [ deploydiscourse ]

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REPOSITORY: joaooxoc/transitionportugal-web
  REGISTRY_HOSTNAME: registry.digitalocean.com/photosapi
  DEPLOYMENT_NAME: tp-discourse-deploy
  DO_CLUSTER: k8s-photos
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  DO_EXTERNAL_IP: ${{secrets.DIGITALOCEAN_EXTERNAL_IP}}
  DIGITALOCEAN_LOADBALANCER_ID: ${{secrets.DIGITALOCEAN_LOADBALANCER_ID}}
  PV_DEPLOYMENT_FILENAME: discourse_persistent_volumes.yml
  APIS_DEPLOYMENT_FILE_NAME: discourse_deploy_pods.yml
  REDIS_DEPLOYMENT_FILE_NAME: discourse_deploy_redis_pod.yml
  INGRESSES_DEPLOYMENT_FILE_NAME: discourse_ingresses.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 6000
      
    - name: authenticate to DO
      run: doctl auth init

    - name: Save DigitalOcean kubeconfig
      run: doctl -t $DIGITALOCEAN_ACCESS_TOKEN k8s cluster config save $DO_CLUSTER
      
    - name: deploy persistent volumes in DO
      run: kubectl apply -f $GITHUB_WORKSPACE/$PV_DEPLOYMENT_FILENAME
    
    - name: Update ingresses deployment file
      run: sed -i "s|<EXTERNAL_DO_IP>|$DO_EXTERNAL_IP|" $GITHUB_WORKSPACE/$INGRESSES_DEPLOYMENT_FILE_NAME && sed -i "s|<DO_LOADBALANCER_ID>|$DIGITALOCEAN_LOADBALANCER_ID|" $GITHUB_WORKSPACE/$INGRESSES_DEPLOYMENT_FILE_NAME
      
    - name: process discourse environment variables
      run: kubectl delete secret tpdiscourse-data --ignore-not-found && kubectl create secret generic tpdiscourse-data --from-literal=discourse-password=${{secrets.DISCOURSE_USER_PASSWORD}} --from-literal=redis-password=${{secrets.DISCOURSE_REDIS_PASSWORD}} --from-literal=database-host=${{secrets.DISCOURSE_DB_HOST}} --from-literal=database-port=${{secrets.DISCOURSE_DB_PORT}} --from-literal=database-name=${{secrets.DISCOURSE_DB_NAME}} --from-literal=database-user=${{secrets.DISCOURSE_DB_USER}} --from-literal=database-password=${{secrets.DISCOURSE_DB_PASSWORD}}

      
    - name: Deploy services and ingresses to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/$INGRESSES_DEPLOYMENT_FILE_NAME
    
    - name: Deploy REDIS to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/$REDIS_DEPLOYMENT_FILE_NAME
      
    - name: Deploy discourse to DigitalOcean Kubernetes

      run: kubectl apply -f $GITHUB_WORKSPACE/$APIS_DEPLOYMENT_FILE_NAME

    - name: Verify deployment of the discourse pod
      run: kubectl rollout status deployment/$DEPLOYMENT_NAME
